### ISSUE TITLE
Unable to import SMD

### ISSUE THREAD

**Issue by chrisall76** [jam1garner/Smash-4-Bone-Animator#7]
When opening SMD for bones or animations, it gives an error.

Version: Windows 10
Date: 10/10/2016
.NET Version: 4.5.2

Error:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.FormatException: Input string was not in a correct format.
>    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
>    at VBN_Editor.SMD.read(String fname, SkelAnimation a, VBN v)
>    at VBN_Editor.MainForm.openVBNToolStripMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Ploaj** [comment]
Could you provide the file?

**Comment by chrisall76** [comment]
Just tried again with a new smd and it worked fine, one I used to test was probably broke.

**Comment by Ploaj** [comment]
If you encounter a broken one again, then upload it somewhere and we can perhaps fix what broke on import. SMD support is still finicky after all.
