### ISSUE TITLE
Exported .anim files hang Maya forever.

### ISSUE THREAD

**Issue by TabuuForteAkugun** [jam1garner/Smash-4-Bone-Animator#9]
I wanted to try something in Maya but most animation exports simply make Maya stop responding and hang indefinitely. I had success with Wait1.omo from Main.pac but since then it stopped working.

Example exported files: Wait2 and Wait3 from Mario's main.pac.

[Anim_Test.zip](https://github.com/jam1garner/Smash-4-Bone-Animator/files/530243/Anim_Test.zip)

**Comment by TabuuForteAkugun** [comment]
So I looked into this more.

Maya doesn't seem to like .anim converted from OMO longer than 60 frames. Ends the same way eacg time: Hangs for like 3 hours and then turns up nothing, and I can't close the program even via End task.

**Comment by Ploaj** [comment]
This has been more or less fixed for now. If any others cause hanging then reopen it.
